name: Build Jekyll and deploy Github page

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: docker.io/jekyll/minimal
    steps:
    - run: apk add rsync
    - uses: actions/checkout@v3
    - run: chown 1000:1000 -R .
    - run: bundle install
    - run: jekyll build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site # The folder the action should deploy.

    # - name: Init new repo in dist folder and commit generated files
    #   run: |
    #     git config --global --add safe.directory '*'
    #     cd _site
    #     git init
    #     git add -A
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git commit -m 'deploy'

    # - name: Force push to destination branch
    #   uses: ad-m/github-push-action@v0.5.0
    #   with:
    #     # Token for the repo
    #     # Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     # Destination branch to push changes
    #     branch: gh-pages
    #     # Use force push to fully overwrite the destination branch
    #     force: true
    #     # We have to push from the folder where files were generated.
    #     # Same were the new repo was initialized in the previous step
    #     directory: ./_site